language: go

services: docker
go:
  - 1.12.x
  - master

go_import_path: fast
before_script: docker run -d --name jaeger
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411
  -p 5775:5775/udp
  -p 6831:6831/udp
  -p 6832:6832/udp
  -p 5778:5778
  -p 16686:16686
  -p 14268:14268
  -p 9411:9411
  jaegertracing/all-in-one:1.13
script: go test -v ./... -tags "jaeger" -race -cover